name: safarni
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.1
  geolocator: ^12.0.0
  google_maps_flutter: ^2.2.5

  flutter_rating_bar: ^4.0.1
  dropdown_search: ^6.0.2
  dotted_line: ^3.2.3

  pin_code_fields: ^8.0.1
  smooth_page_indicator: ^1.2.1
  flutter_native_splash: ^2.4.6
  flutter_bloc: ^9.1.1
  auto_size_text: ^3.0.0
  intl: ^0.20.2
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it: ^8.2.0


dev_dependencies:
  curved_navigation_bar: ^1.0.6
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  persistent_bottom_nav_bar_v2: ^6.1.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    
     
  #   - images/a_dot_ham.jpeg

  #   - images/a_dot_ham.jpeg



  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf



flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: assets.dart

  field_prefix: null
   
