// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

class AppAssets {
  const AppAssets._();

  /// {@macro assets_generator.assets_images_arc_de_triomphe_png.preview}
  static const String assets_images_arc_de_triomphe_png =
      'assets/images/Arc de Triomphe.png';

  /// {@macro assets_generator.assets_images_centre_pompidou_png.preview}
  static const String assets_images_centre_pompidou_png =
      'assets/images/Centre_Pompidou.png';

  /// {@macro assets_generator.assets_images__file_placeholder_png.preview}
  static const String assets_images__file_placeholder_png =
      'assets/images/_File Placeholder.png';

  /// {@macro assets_generator.assets_images_louvre_png.preview}
  static const String assets_images_louvre_png = 'assets/images/louvre.png';

  /// {@macro assets_generator.assets_images_notre_dame_png.preview}
  static const String assets_images_notre_dame_png =
      'assets/images/notre_dame.png';
}
