// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

class AppAssets {
  const AppAssets._();

  /// {@macro assets_generator.assets_images_arc_de_triomphe_png.preview}
  static const String assets_images_arc_de_triomphe_png =
      'assets/images/Arc de Triomphe.png';

  /// {@macro assets_generator.assets_images_centre_pompidou_png.preview}
  static const String assets_images_centre_pompidou_png =
      'assets/images/Centre_Pompidou.png';

  /// {@macro assets_generator.assets_images__file_placeholder_png.preview}
  static const String assets_images__file_placeholder_png =
      'assets/images/_File Placeholder.png';

  /// {@macro assets_generator.assets_images_louvre_png.preview}
  static const String assets_images_louvre_png = 'assets/images/louvre.png';

  /// {@macro assets_generator.assets_images_notre_dame_png.preview}
  static const String assets_images_notre_dame_png =
      'assets/images/notre_dame.png';
}
class AppAssets{

  static final String homeMainPhoto="assets/images/home1.png";
  static final String homeFlightPhoto="assets/images/flight.png";
  static final String homeCarPhoto="assets/images/car.png";
  static final String homeHotelPhoto="assets/images/hotel.png";
  static final String homeTourPhoto="assets/images/tour.png";

  static final String homePyramidPhoto="assets/images/pyr.png";
  static final String homeCitadelPhoto="assets/images/citadel.png";
  static final String fayoumPhoto="assets/images/fay.png";
  static final String luxuryPhoto="assets/images/lux.png";
  static final String dahabPhoto="assets/images/dahab.png";

  static final String myPhoto="assets/images/my_photo.png";
  static final String iconCompare="assets/images/compare.png";

}
